export const REGION_LIST = [
    { name: '수원시' },
    { name: '용인시' },
    { name: '화성시' },
    { name: '성남시' },
    { name: '부천시' },
    { name: '안산시' },
    { name: '평택시' },
    { name: '안양시' },
    { name: '시흥시' },
    { name: '김포시' },
    { name: '광주시' },
    { name: '하남시' },
    { name: '광명시' },
    { name: '군포시' },
    { name: '오산시' },
    { name: '이천시' },
    { name: '안성시' },
    { name: '의왕시' },
    { name: '양평군' },
    { name: '여주시' },
    { name: '과천시' },
    { name: '고양시' },
    { name: '남양주시' },
    { name: '파주시' },
    { name: '의정부시' },
    { name: '양주시' },
    { name: '구리시' },
    { name: '포천시' },
    { name: '동두천시' },
    { name: '가평군' },
    { name: '연천군' },
];

// 위 REGION LIST와 순서 같음
export const REGION_LIST_ENG = [
    { color: '#51247A', alt: '수원시', name: 'suwon' },
    { color: '#009544', alt: '용인시', name: 'yogin' },
    { color: '#F58220', alt: '화성시', name: 'hs' },
    { color: '#FFCB05', alt: '성남시', name: 'seongnam', cash: true, mobile: true },
    { color: '#0091D4', alt: '부천시', name: 'bucheon' },
    { color: '#005596', alt: '안산시', name: 'ansan', cash: true },
    { color: '#004A99', alt: '평택시', name: 'pt', cash: true },
    { color: '#004990', alt: '안양시', name: 'anyang', cash: true },
    { color: '#6BB745', alt: '시흥시', name: 'siheong', cash: true },
    { color: '#00A1E9', alt: '김포시', name: 'gimpo', mobile: true },
    { color: '#ED1C24', alt: '광주시', name: 'gwangju' },
    { color: '#00A29A', alt: '하남시', name: 'hanam' },
    { color: '#FFD400', alt: '광명시', name: 'gm' },
    { color: '#008D44', alt: '군포시', name: 'gunpo' },
    { color: '#FFCE00', alt: '오산시', name: 'osan' },
    { color: '#006DB7', alt: '이천시', name: 'icheon' },
    { color: '#004F9B', alt: '안성시', name: 'anseong' },
    { color: '#34B149', alt: '의왕시', name: 'uiwang', cash: true },
    { color: '#009640', alt: '양평군', name: 'yangpung' },
    { color: '#0082CA', alt: '여주시', name: 'yeoju' },
    { color: '#009A44', alt: '과천시', name: 'gc', cash: true },
    { color: '#00AEEF', alt: '고양시', name: 'goyang' },
    { color: '#86BC25', alt: '남양주시', name: 'nyj' },
    { color: '#0059B3', alt: '파주시', name: 'paju' },
    { color: '#FF6600', alt: '의정부시', name: 'ujb' },
    { color: '#0072BC', alt: '양주시', name: 'yangju' },
    { color: '#00A14B', alt: '구리시', name: 'guri' },
    { color: '#006BB6', alt: '포천시', name: 'pocheon', cash: true },
    { color: '#F39800', alt: '동두천시', name: 'ddc' },
    { color: '#20AC4B', alt: '가평군', name: 'gapung', mobile: true },
    { color: '#0054A6', alt: '연천군', name: 'yeoncheon' },
];
